<?php
/**
 * Country dial codes as data array.
 *
 * @package OceanWP_Child
 */

defined( 'ABSPATH' ) || exit;

/**
 * @return array<int, array{value:string,label:string}>
 */
function xe36_booking_countries() {
	return array(
		array( 'value' => 'Vietnam +84', 'label' => 'Vietnam (+84)' ),
		array( 'value' => 'Afghanistan +93', 'label' => 'Afghanistan (+93)' ),
		array( 'value' => 'Albania +355', 'label' => 'Albania (+355)' ),
		array( 'value' => 'Algeria +213', 'label' => 'Algeria (+213)' ),
		array( 'value' => 'Andorra +376', 'label' => 'Andorra (+376)' ),
		array( 'value' => 'Angola +244', 'label' => 'Angola (+244)' ),
		array( 'value' => 'Antigua and Barbuda +1-268', 'label' => 'Antigua and Barbuda (+1-268)' ),
		array( 'value' => 'Argentina +54', 'label' => 'Argentina (+54)' ),
		array( 'value' => 'Armenia +374', 'label' => 'Armenia (+374)' ),
		array( 'value' => 'Australia +61', 'label' => 'Australia (+61)' ),
		array( 'value' => 'Austria +43', 'label' => 'Austria (+43)' ),
		array( 'value' => 'Azerbaijan +994', 'label' => 'Azerbaijan (+994)' ),
		array( 'value' => 'Bahamas +1-242', 'label' => 'Bahamas (+1-242)' ),
		array( 'value' => 'Bahrain +973', 'label' => 'Bahrain (+973)' ),
		array( 'value' => 'Bangladesh +880', 'label' => 'Bangladesh (+880)' ),
		array( 'value' => 'Barbados +1-246', 'label' => 'Barbados (+1-246)' ),
		array( 'value' => 'Belarus +375', 'label' => 'Belarus (+375)' ),
		array( 'value' => 'Belgium +32', 'label' => 'Belgium (+32)' ),
		array( 'value' => 'Belize +501', 'label' => 'Belize (+501)' ),
		array( 'value' => 'Benin +229', 'label' => 'Benin (+229)' ),
		array( 'value' => 'Bhutan +975', 'label' => 'Bhutan (+975)' ),
		array( 'value' => 'Bolivia +591', 'label' => 'Bolivia (+591)' ),
		array( 'value' => 'Bosnia and Herzegovina +387', 'label' => 'Bosnia and Herzegovina (+387)' ),
		array( 'value' => 'Botswana +267', 'label' => 'Botswana (+267)' ),
		array( 'value' => 'Brazil +55', 'label' => 'Brazil (+55)' ),
		array( 'value' => 'Brunei +673', 'label' => 'Brunei (+673)' ),
		array( 'value' => 'Bulgaria +359', 'label' => 'Bulgaria (+359)' ),
		array( 'value' => 'Burkina Faso +226', 'label' => 'Burkina Faso (+226)' ),
		array( 'value' => 'Burundi +257', 'label' => 'Burundi (+257)' ),
		array( 'value' => 'Cambodia +855', 'label' => 'Cambodia (+855)' ),
		array( 'value' => 'Cameroon +237', 'label' => 'Cameroon (+237)' ),
		array( 'value' => 'Canada +1', 'label' => 'Canada (+1)' ),
		array( 'value' => 'Cape Verde +238', 'label' => 'Cape Verde (+238)' ),
		array( 'value' => 'Central African Republic +236', 'label' => 'Central African Republic (+236)' ),
		array( 'value' => 'Chad +235', 'label' => 'Chad (+235)' ),
		array( 'value' => 'Chile +56', 'label' => 'Chile (+56)' ),
		array( 'value' => 'China +86', 'label' => 'China (+86)' ),
		array( 'value' => 'Colombia +57', 'label' => 'Colombia (+57)' ),
		array( 'value' => 'Comoros +269', 'label' => 'Comoros (+269)' ),
		array( 'value' => 'Congo +242', 'label' => 'Congo (+242)' ),
		array( 'value' => 'Congo, Democratic Republic +243', 'label' => 'Congo, Democratic Republic (+243)' ),
		array( 'value' => 'Costa Rica +506', 'label' => 'Costa Rica (+506)' ),
		array( 'value' => 'Croatia +385', 'label' => 'Croatia (+385)' ),
		array( 'value' => 'Cuba +53', 'label' => 'Cuba (+53)' ),
		array( 'value' => 'Cyprus +357', 'label' => 'Cyprus (+357)' ),
		array( 'value' => 'Czech Republic +420', 'label' => 'Czech Republic (+420)' ),
		array( 'value' => 'Denmark +45', 'label' => 'Denmark (+45)' ),
		array( 'value' => 'Djibouti +253', 'label' => 'Djibouti (+253)' ),
		array( 'value' => 'Dominica +1-767', 'label' => 'Dominica (+1-767)' ),
		array( 'value' => 'Dominican Republic +1-809', 'label' => 'Dominican Republic (+1-809)' ),
		array( 'value' => 'Ecuador +593', 'label' => 'Ecuador (+593)' ),
		array( 'value' => 'Egypt +20', 'label' => 'Egypt (+20)' ),
		array( 'value' => 'El Salvador +503', 'label' => 'El Salvador (+503)' ),
		array( 'value' => 'Equatorial Guinea +240', 'label' => 'Equatorial Guinea (+240)' ),
		array( 'value' => 'Eritrea +291', 'label' => 'Eritrea (+291)' ),
		array( 'value' => 'Estonia +372', 'label' => 'Estonia (+372)' ),
		array( 'value' => 'Eswatini +268', 'label' => 'Eswatini (+268)' ),
		array( 'value' => 'Ethiopia +251', 'label' => 'Ethiopia (+251)' ),
		array( 'value' => 'Fiji +679', 'label' => 'Fiji (+679)' ),
		array( 'value' => 'Finland +358', 'label' => 'Finland (+358)' ),
		array( 'value' => 'France +33', 'label' => 'France (+33)' ),
		array( 'value' => 'Gabon +241', 'label' => 'Gabon (+241)' ),
		array( 'value' => 'Gambia +220', 'label' => 'Gambia (+220)' ),
		array( 'value' => 'Georgia +995', 'label' => 'Georgia (+995)' ),
		array( 'value' => 'Germany +49', 'label' => 'Germany (+49)' ),
		array( 'value' => 'Ghana +233', 'label' => 'Ghana (+233)' ),
		array( 'value' => 'Greece +30', 'label' => 'Greece (+30)' ),
		array( 'value' => 'Grenada +1-473', 'label' => 'Grenada (+1-473)' ),
		array( 'value' => 'Guatemala +502', 'label' => 'Guatemala (+502)' ),
		array( 'value' => 'Guinea +224', 'label' => 'Guinea (+224)' ),
		array( 'value' => 'Guinea-Bissau +245', 'label' => 'Guinea-Bissau (+245)' ),
		array( 'value' => 'Guyana +592', 'label' => 'Guyana (+592)' ),
		array( 'value' => 'Haiti +509', 'label' => 'Haiti (+509)' ),
		array( 'value' => 'Honduras +504', 'label' => 'Honduras (+504)' ),
		array( 'value' => 'Hungary +36', 'label' => 'Hungary (+36)' ),
		array( 'value' => 'Iceland +354', 'label' => 'Iceland (+354)' ),
		array( 'value' => 'India +91', 'label' => 'India (+91)' ),
		array( 'value' => 'Indonesia +62', 'label' => 'Indonesia (+62)' ),
		array( 'value' => 'Iran +98', 'label' => 'Iran (+98)' ),
		array( 'value' => 'Iraq +964', 'label' => 'Iraq (+964)' ),
		array( 'value' => 'Ireland +353', 'label' => 'Ireland (+353)' ),
		array( 'value' => 'Israel +972', 'label' => 'Israel (+972)' ),
		array( 'value' => 'Italy +39', 'label' => 'Italy (+39)' ),
		array( 'value' => 'Jamaica +1-876', 'label' => 'Jamaica (+1-876)' ),
		array( 'value' => 'Japan +81', 'label' => 'Japan (+81)' ),
		array( 'value' => 'Jordan +962', 'label' => 'Jordan (+962)' ),
		array( 'value' => 'Kazakhstan +7', 'label' => 'Kazakhstan (+7)' ),
		array( 'value' => 'Kenya +254', 'label' => 'Kenya (+254)' ),
		array( 'value' => 'Kiribati +686', 'label' => 'Kiribati (+686)' ),
		array( 'value' => 'Kuwait +965', 'label' => 'Kuwait (+965)' ),
		array( 'value' => 'Kyrgyzstan +996', 'label' => 'Kyrgyzstan (+996)' ),
		array( 'value' => 'Laos +856', 'label' => 'Laos (+856)' ),
		array( 'value' => 'Latvia +371', 'label' => 'Latvia (+371)' ),
		array( 'value' => 'Lebanon +961', 'label' => 'Lebanon (+961)' ),
		array( 'value' => 'Lesotho +266', 'label' => 'Lesotho (+266)' ),
		array( 'value' => 'Liberia +231', 'label' => 'Liberia (+231)' ),
		array( 'value' => 'Libya +218', 'label' => 'Libya (+218)' ),
		array( 'value' => 'Liechtenstein +423', 'label' => 'Liechtenstein (+423)' ),
		array( 'value' => 'Lithuania +370', 'label' => 'Lithuania (+370)' ),
		array( 'value' => 'Luxembourg +352', 'label' => 'Luxembourg (+352)' ),
		array( 'value' => 'Madagascar +261', 'label' => 'Madagascar (+261)' ),
		array( 'value' => 'Malawi +265', 'label' => 'Malawi (+265)' ),
		array( 'value' => 'Malaysia +60', 'label' => 'Malaysia (+60)' ),
		array( 'value' => 'Maldives +960', 'label' => 'Maldives (+960)' ),
		array( 'value' => 'Mali +223', 'label' => 'Mali (+223)' ),
		array( 'value' => 'Malta +356', 'label' => 'Malta (+356)' ),
		array( 'value' => 'Marshall Islands +692', 'label' => 'Marshall Islands (+692)' ),
		array( 'value' => 'Mauritania +222', 'label' => 'Mauritania (+222)' ),
		array( 'value' => 'Mauritius +230', 'label' => 'Mauritius (+230)' ),
		array( 'value' => 'Mexico +52', 'label' => 'Mexico (+52)' ),
		array( 'value' => 'Micronesia +691', 'label' => 'Micronesia (+691)' ),
		array( 'value' => 'Moldova +373', 'label' => 'Moldova (+373)' ),
		array( 'value' => 'Monaco +377', 'label' => 'Monaco (+377)' ),
		array( 'value' => 'Mongolia +976', 'label' => 'Mongolia (+976)' ),
		array( 'value' => 'Montenegro +382', 'label' => 'Montenegro (+382)' ),
		array( 'value' => 'Morocco +212', 'label' => 'Morocco (+212)' ),
		array( 'value' => 'Mozambique +258', 'label' => 'Mozambique (+258)' ),
		array( 'value' => 'Myanmar +95', 'label' => 'Myanmar (+95)' ),
		array( 'value' => 'Namibia +264', 'label' => 'Namibia (+264)' ),
		array( 'value' => 'Nauru +674', 'label' => 'Nauru (+674)' ),
		array( 'value' => 'Nepal +977', 'label' => 'Nepal (+977)' ),
		array( 'value' => 'Netherlands +31', 'label' => 'Netherlands (+31)' ),
		array( 'value' => 'New Zealand +64', 'label' => 'New Zealand (+64)' ),
		array( 'value' => 'Nicaragua +505', 'label' => 'Nicaragua (+505)' ),
		array( 'value' => 'Niger +227', 'label' => 'Niger (+227)' ),
		array( 'value' => 'Nigeria +234', 'label' => 'Nigeria (+234)' ),
		array( 'value' => 'North Korea +850', 'label' => 'North Korea (+850)' ),
		array( 'value' => 'North Macedonia +389', 'label' => 'North Macedonia (+389)' ),
		array( 'value' => 'Norway +47', 'label' => 'Norway (+47)' ),
		array( 'value' => 'Oman +968', 'label' => 'Oman (+968)' ),
		array( 'value' => 'Pakistan +92', 'label' => 'Pakistan (+92)' ),
		array( 'value' => 'Palau +680', 'label' => 'Palau (+680)' ),
		array( 'value' => 'Panama +507', 'label' => 'Panama (+507)' ),
		array( 'value' => 'Papua New Guinea +675', 'label' => 'Papua New Guinea (+675)' ),
		array( 'value' => 'Paraguay +595', 'label' => 'Paraguay (+595)' ),
		array( 'value' => 'Peru +51', 'label' => 'Peru (+51)' ),
		array( 'value' => 'Philippines +63', 'label' => 'Philippines (+63)' ),
		array( 'value' => 'Poland +48', 'label' => 'Poland (+48)' ),
		array( 'value' => 'Portugal +351', 'label' => 'Portugal (+351)' ),
		array( 'value' => 'Qatar +974', 'label' => 'Qatar (+974)' ),
		array( 'value' => 'Romania +40', 'label' => 'Romania (+40)' ),
		array( 'value' => 'Russia +7', 'label' => 'Russia (+7)' ),
		array( 'value' => 'Rwanda +250', 'label' => 'Rwanda (+250)' ),
		array( 'value' => 'Saint Kitts and Nevis +1-869', 'label' => 'Saint Kitts and Nevis (+1-869)' ),
		array( 'value' => 'Saint Lucia +1-758', 'label' => 'Saint Lucia (+1-758)' ),
		array( 'value' => 'Saint Vincent and the Grenadines +1-784', 'label' => 'Saint Vincent and the Grenadines (+1-784)' ),
		array( 'value' => 'Samoa +685', 'label' => 'Samoa (+685)' ),
		array( 'value' => 'San Marino +378', 'label' => 'San Marino (+378)' ),
		array( 'value' => 'Sao Tome and Principe +239', 'label' => 'Sao Tome and Principe (+239)' ),
		array( 'value' => 'Saudi Arabia +966', 'label' => 'Saudi Arabia (+966)' ),
		array( 'value' => 'Senegal +221', 'label' => 'Senegal (+221)' ),
		array( 'value' => 'Serbia +381', 'label' => 'Serbia (+381)' ),
		array( 'value' => 'Seychelles +248', 'label' => 'Seychelles (+248)' ),
		array( 'value' => 'Sierra Leone +232', 'label' => 'Sierra Leone (+232)' ),
		array( 'value' => 'Singapore +65', 'label' => 'Singapore (+65)' ),
		array( 'value' => 'Slovakia +421', 'label' => 'Slovakia (+421)' ),
		array( 'value' => 'Slovenia +386', 'label' => 'Slovenia (+386)' ),
		array( 'value' => 'Solomon Islands +677', 'label' => 'Solomon Islands (+677)' ),
		array( 'value' => 'Somalia +252', 'label' => 'Somalia (+252)' ),
		array( 'value' => 'South Africa +27', 'label' => 'South Africa (+27)' ),
		array( 'value' => 'South Korea +82', 'label' => 'South Korea (+82)' ),
		array( 'value' => 'South Sudan +211', 'label' => 'South Sudan (+211)' ),
		array( 'value' => 'Spain +34', 'label' => 'Spain (+34)' ),
		array( 'value' => 'Sri Lanka +94', 'label' => 'Sri Lanka (+94)' ),
		array( 'value' => 'Sudan +249', 'label' => 'Sudan (+249)' ),
		array( 'value' => 'Suriname +597', 'label' => 'Suriname (+597)' ),
		array( 'value' => 'Sweden +46', 'label' => 'Sweden (+46)' ),
		array( 'value' => 'Switzerland +41', 'label' => 'Switzerland (+41)' ),
		array( 'value' => 'Syria +963', 'label' => 'Syria (+963)' ),
		array( 'value' => 'Taiwan +886', 'label' => 'Taiwan (+886)' ),
		array( 'value' => 'Tajikistan +992', 'label' => 'Tajikistan (+992)' ),
		array( 'value' => 'Tanzania +255', 'label' => 'Tanzania (+255)' ),
		array( 'value' => 'Thailand +66', 'label' => 'Thailand (+66)' ),
		array( 'value' => 'Timor-Leste +670', 'label' => 'Timor-Leste (+670)' ),
		array( 'value' => 'Togo +228', 'label' => 'Togo (+228)' ),
		array( 'value' => 'Tonga +676', 'label' => 'Tonga (+676)' ),
		array( 'value' => 'Trinidad and Tobago +1-868', 'label' => 'Trinidad and Tobago (+1-868)' ),
		array( 'value' => 'Tunisia +216', 'label' => 'Tunisia (+216)' ),
		array( 'value' => 'Turkey +90', 'label' => 'Turkey (+90)' ),
		array( 'value' => 'Turkmenistan +993', 'label' => 'Turkmenistan (+993)' ),
		array( 'value' => 'Tuvalu +688', 'label' => 'Tuvalu (+688)' ),
		array( 'value' => 'Uganda +256', 'label' => 'Uganda (+256)' ),
		array( 'value' => 'Ukraine +380', 'label' => 'Ukraine (+380)' ),
		array( 'value' => 'United Arab Emirates +971', 'label' => 'United Arab Emirates (+971)' ),
		array( 'value' => 'United Kingdom +44', 'label' => 'United Kingdom (+44)' ),
		array( 'value' => 'United States +1', 'label' => 'United States (+1)' ),
		array( 'value' => 'Uruguay +598', 'label' => 'Uruguay (+598)' ),
		array( 'value' => 'Uzbekistan +998', 'label' => 'Uzbekistan (+998)' ),
		array( 'value' => 'Vanuatu +678', 'label' => 'Vanuatu (+678)' ),
		array( 'value' => 'Vatican City +379', 'label' => 'Vatican City (+379)' ),
		array( 'value' => 'Venezuela +58', 'label' => 'Venezuela (+58)' ),
		array( 'value' => 'Yemen +967', 'label' => 'Yemen (+967)' ),
		array( 'value' => 'Zambia +260', 'label' => 'Zambia (+260)' ),
		array( 'value' => 'Zimbabwe +263', 'label' => 'Zimbabwe (+263)' ),
	);
}
