<?php
/**
 * ACF field group: Trang chủ (options).
 *
 * Stable field `key` / `name` values — do not rename without migration.
 *
 * @package OceanWP_Child
 */

defined( 'ABSPATH' ) || exit;

/**
 * Register homepage field group.
 */
function xe36_acf_register_homepage_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	$sections       = require xe36_theme_path( 'inc/homepage/config.php' );
	$section_fields = array();

	foreach ( $sections as $slug => $section ) {
		$section_fields[] = array(
			'key'           => 'field_xe36_section_' . $slug . '_enabled',
			'label'         => $section['label'],
			'name'          => 'section_' . $slug . '_enabled',
			'type'          => 'true_false',
			'ui'            => 1,
			'default_value' => ! empty( $section['enabled'] ) ? 1 : 0,
		);
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_xe36_homepage',
			'title'                 => 'Trang chủ — Xe 36',
			'fields'                => array_merge(
				array(
					array(
						'key'   => 'field_xe36_tab_hero',
						'label' => 'Hero / Banner',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'   => 'field_xe36_hero_title',
						'label' => 'Thương hiệu (dòng trên)',
						'name'  => 'hero_title',
						'type'  => 'text',
						'instructions' => 'Ví dụ: Xe 36 Limousine',
					),
					array(
						'key'   => 'field_xe36_hero_subtitle',
						'label' => 'Tiêu đề tuyến',
						'name'  => 'hero_subtitle',
						'type'  => 'textarea',
						'rows'  => 2,
						'instructions' => 'Ví dụ: Tuyến Hà Nội ⇌ TP Thanh Hóa / Sầm Sơn / Hải Tiến',
					),
					array(
						'key'   => 'field_xe36_hero_highlight',
						'label' => 'Dòng nhấn',
						'name'  => 'hero_highlight',
						'type'  => 'text',
						'instructions' => 'Ví dụ: Đưa đón tận nơi',
					),
					array(
						'key'          => 'field_xe36_hero_facts',
						'label'        => 'Thông tin nổi bật',
						'name'         => 'hero_facts',
						'type'         => 'textarea',
						'rows'         => 5,
						'instructions' => 'Mỗi dòng một ý (cao tốc, tần suất, giờ chạy, thời gian di chuyển…).',
					),
					array(
						'key'           => 'field_xe36_hero_image',
						'label'         => 'Ảnh banner',
						'name'          => 'hero_image',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'library'       => 'all',
						'instructions'  => 'Gợi ý: ảnh ngang 1920×900–1080, JPG/WebP &lt; 400KB. Vùng trái tối hơn để chữ dễ đọc.',
					),
					array(
						'key'     => 'field_xe36_hero_show_form',
						'label'   => 'Form đặt vé',
						'name'    => '',
						'type'    => 'message',
						'message' => 'Form đặt vé nằm ở <strong>section Đặt vé</strong> ngay dưới Hero. Nút “Đặt vé ngay” nên trỏ tới <code>#home-booking</code>. Bật/tắt section trong tab “Bật / tắt section”.',
					),
					array(
						'key'          => 'field_xe36_hero_cta_text',
						'label'        => 'Nút CTA chính — chữ',
						'name'         => 'hero_cta_text',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Đặt vé ngay. Link mặc định #home-booking (cuộn tới form bên dưới).',
					),
					array(
						'key'          => 'field_xe36_hero_cta_url',
						'label'        => 'Nút CTA chính — link',
						'name'         => 'hero_cta_url',
						'type'         => 'text',
						'instructions' => 'Được dùng: <code>#home-booking</code>, đường dẫn tương đối, hoặc URL đầy đủ (https://…).',
					),
					array(
						'key'          => 'field_xe36_hero_cta2_text',
						'label'        => 'Nút gọi hotline — chữ',
						'name'         => 'hero_cta2_text',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Gọi hotline.',
					),
					array(
						'key'          => 'field_xe36_hero_cta2_url',
						'label'        => 'Nút gọi hotline — link',
						'name'         => 'hero_cta2_url',
						'type'         => 'text',
						'instructions' => 'Ví dụ: <code>tel:19001234</code>.',
					),
					array(
						'key'          => 'field_xe36_hero_cta3_text',
						'label'        => 'Nút Zalo — chữ',
						'name'         => 'hero_cta3_text',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Nhắn Zalo.',
					),
					array(
						'key'          => 'field_xe36_hero_cta3_url',
						'label'        => 'Nút Zalo — link',
						'name'         => 'hero_cta3_url',
						'type'         => 'text',
						'instructions' => 'Để trống sẽ dùng link Zalo ở <strong>Trang chủ → Liên hệ</strong>.',
					),
					array(
						'key'   => 'field_xe36_tab_booking_labels',
						'label' => 'Form đặt vé',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'     => 'field_xe36_booking_labels_message',
						'label'   => '',
						'name'    => '',
						'type'    => 'message',
						'message' => 'Chỉ sửa <strong>chữ hiển thị</strong> và <strong>giá vé</strong> trên form. Danh sách tuyến (Hà Nội ↔ Thanh Hóa / Sầm Sơn / Hải Tiến) do code quy định.',
					),
					array(
						'key'   => 'field_xe36_booking_section_title',
						'label' => 'Tiêu đề section đặt vé',
						'name'  => 'booking_section_title',
						'type'  => 'text',
						'instructions' => 'Ví dụ: Đặt vé Limousine Hà Nội ⇌ Thanh Hóa nhanh',
					),
					array(
						'key'          => 'field_xe36_booking_process_steps',
						'label'        => 'Quy trình gửi yêu cầu đặt vé (mỗi dòng 1 bước)',
						'name'         => 'booking_process_steps',
						'type'         => 'textarea',
						'rows'         => 4,
					),
					array(
						'key'   => 'field_xe36_booking_process_note',
						'label' => 'Lưu ý nhỏ dưới quy trình',
						'name'  => 'booking_process_note',
						'type'  => 'textarea',
						'rows'  => 2,
					),
					array(
						'key'   => 'field_xe36_booking_form_title',
						'label' => 'Tiêu đề trong form (ẩn trên homepage)',
						'name'  => 'booking_form_title',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_label_route',
						'label' => 'Nhãn — Tuyến',
						'name'  => 'booking_label_route',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_label_date',
						'label' => 'Nhãn — Ngày đi',
						'name'  => 'booking_label_date',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_label_time',
						'label' => 'Nhãn — Giờ đi',
						'name'  => 'booking_label_time',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_label_name',
						'label' => 'Nhãn — Họ tên',
						'name'  => 'booking_label_name',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_label_phone',
						'label' => 'Nhãn — Số điện thoại',
						'name'  => 'booking_label_phone',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_label_seat',
						'label' => 'Nhãn — Ghế muốn ngồi',
						'name'  => 'booking_label_seat',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_label_tickets',
						'label' => 'Nhãn — Số vé',
						'name'  => 'booking_label_tickets',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_submit_text',
						'label' => 'Nút gửi — chữ',
						'name'  => 'booking_submit_text',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_booking_success_text',
						'label' => 'Thông báo thành công',
						'name'  => 'booking_success_text',
						'type'  => 'textarea',
						'rows'  => 2,
					),
					array(
						'key'     => 'field_xe36_booking_prices_message',
						'label'   => '',
						'name'    => '',
						'type'    => 'message',
						'message' => '<strong>Giá vé (VNĐ)</strong> — giá gốc cho tuyến Hà Nội ↔ TP Thanh Hóa. Tuyến Sầm Sơn / Hải Tiến cộng thêm phụ phí bên dưới. Card lộ trình hiển thị giá thấp nhất.',
					),
					array(
						'key'           => 'field_xe36_booking_price_front',
						'label'         => 'Giá ghế đầu',
						'name'          => 'booking_price_front',
						'type'          => 'number',
						'min'           => 0,
						'step'          => 1000,
						'append'        => 'đ',
						'default_value' => 260000,
					),
					array(
						'key'           => 'field_xe36_booking_price_middle',
						'label'         => 'Giá ghế giữa',
						'name'          => 'booking_price_middle',
						'type'          => 'number',
						'min'           => 0,
						'step'          => 1000,
						'append'        => 'đ',
						'default_value' => 280000,
					),
					array(
						'key'           => 'field_xe36_booking_price_back',
						'label'         => 'Giá ghế cuối',
						'name'          => 'booking_price_back',
						'type'          => 'number',
						'min'           => 0,
						'step'          => 1000,
						'append'        => 'đ',
						'default_value' => 260000,
					),
					array(
						'key'           => 'field_xe36_booking_price_surcharge',
						'label'         => 'Phụ phí Sầm Sơn / Hải Tiến',
						'name'          => 'booking_price_surcharge',
						'type'          => 'number',
						'min'           => 0,
						'step'          => 1000,
						'append'        => 'đ',
						'default_value' => 50000,
						'instructions'  => 'Cộng thêm vào mọi loại ghế khi chọn tuyến Sầm Sơn hoặc Hải Tiến.',
					),
					array(
						'key'   => 'field_xe36_tab_gallery',
						'label' => 'Nội / ngoại thất',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'          => 'field_xe36_gallery_title',
						'label'        => 'Tiêu đề section',
						'name'         => 'gallery_title',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Nội thất, ngoại thất xe Limousine 11 chỗ',
					),
					array(
						'key'           => 'field_xe36_gallery_images',
						'label'         => 'Ảnh nội thất / ngoại thất',
						'name'          => 'gallery_images',
						'type'          => 'gallery',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'insert'        => 'append',
						'library'       => 'all',
						'mime_types'    => 'jpg,jpeg,png,webp',
						'instructions'  => 'Kéo thả để sắp xếp. Slide tự chạy mỗi 3 giây; trên mobile ảnh kế tiếp lộ một phần để vuốt.',
					),
					array(
						'key'   => 'field_xe36_tab_routes',
						'label' => 'Lộ trình phổ biến',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'          => 'field_xe36_routes_title',
						'label'        => 'Tiêu đề section',
						'name'         => 'routes_title',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Lộ trình phổ biến',
					),
					array(
						'key'          => 'field_xe36_routes_cta_text',
						'label'        => 'Chữ nút trên card',
						'name'         => 'routes_cta_text',
						'type'         => 'text',
					),
					array(
						'key'           => 'field_xe36_route_card_img_hn_th',
						'label'         => 'Ảnh — Hà Nội → TP Thanh Hóa',
						'name'          => 'routes_img_hn_th',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'library'       => 'all',
						'instructions'  => 'Ảnh đại diện card lộ trình. Nhớ bấm “Lưu trang chủ” sau khi chọn.',
					),
					array(
						'key'           => 'field_xe36_route_card_img_th_hn',
						'label'         => 'Ảnh — TP Thanh Hóa → Hà Nội',
						'name'          => 'routes_img_th_hn',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'library'       => 'all',
					),
					array(
						'key'           => 'field_xe36_route_card_img_hn_ss',
						'label'         => 'Ảnh — Hà Nội → Sầm Sơn',
						'name'          => 'routes_img_hn_ss',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'library'       => 'all',
					),
					array(
						'key'           => 'field_xe36_route_card_img_ss_hn',
						'label'         => 'Ảnh — Sầm Sơn → Hà Nội',
						'name'          => 'routes_img_ss_hn',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'library'       => 'all',
					),
					array(
						'key'           => 'field_xe36_route_card_img_hn_ht',
						'label'         => 'Ảnh — Hà Nội → Hải Tiến',
						'name'          => 'routes_img_hn_ht',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'library'       => 'all',
					),
					array(
						'key'           => 'field_xe36_route_card_img_ht_hn',
						'label'         => 'Ảnh — Hải Tiến → Hà Nội',
						'name'          => 'routes_img_ht_hn',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'library'       => 'all',
					),
					array(
						'key'   => 'field_xe36_tab_offers',
						'label' => 'Chương trình ưu đãi',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'          => 'field_xe36_offers_title',
						'label'        => 'Tiêu đề section',
						'name'         => 'offers_title',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Chương trình ưu đãi',
					),
					array(
						'key'          => 'field_xe36_offers_items',
						'label'        => 'Danh sách ưu đãi (mỗi dòng 1 mục)',
						'name'         => 'offers_items',
						'type'         => 'textarea',
						'rows'         => 5,
						'instructions' => 'Ví dụ: Khứ hồi trong ngày giảm 20.000đ',
					),
					array(
						'key'          => 'field_xe36_offers_video_url',
						'label'        => 'Link YouTube / Shorts',
						'name'         => 'offers_video_url',
						'type'         => 'url',
						'instructions' => 'Dán link dạng https://www.youtube.com/shorts/... hoặc youtube.com/watch?v=...',
					),
					array(
						'key'   => 'field_xe36_tab_pricing',
						'label' => 'Bảng giá & lịch chạy',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'          => 'field_xe36_pricing_title',
						'label'        => 'Tiêu đề section',
						'name'         => 'pricing_title',
						'type'         => 'text',
					),
					array(
						'key'     => 'field_xe36_pricing_prices_message',
						'label'   => '',
						'name'    => '',
						'type'    => 'message',
						'message' => 'Bảng giá trên trang chủ <strong>tự lấy</strong> từ giá ghế ở tab <strong>Form đặt vé</strong> (ghế đầu / giữa / cuối + phụ phí). Chỉ cần sửa giá ở đó.',
					),
					array(
						'key'   => 'field_xe36_pricing_schedule_title',
						'label' => 'Tiêu đề lịch chạy',
						'name'  => 'pricing_schedule_title',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_pricing_schedule_subtitle',
						'label' => 'Phụ đề lịch chạy',
						'name'  => 'pricing_schedule_subtitle',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_pricing_schedule_route',
						'label' => 'Tuyến trên lịch chạy',
						'name'  => 'pricing_schedule_route',
						'type'  => 'text',
					),
					array(
						'key'          => 'field_xe36_pricing_schedule_morning',
						'label'        => 'Giờ buổi sáng (mỗi dòng 1 giờ)',
						'name'         => 'pricing_schedule_morning',
						'type'         => 'textarea',
						'rows'         => 6,
					),
					array(
						'key'          => 'field_xe36_pricing_schedule_afternoon',
						'label'        => 'Giờ buổi chiều (mỗi dòng 1 giờ)',
						'name'         => 'pricing_schedule_afternoon',
						'type'         => 'textarea',
						'rows'         => 6,
					),
					array(
						'key'   => 'field_xe36_tab_features',
						'label' => 'Lý do chọn xe 36',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'          => 'field_xe36_features_title',
						'label'        => 'Tiêu đề section',
						'name'         => 'features_title',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Lý do chọn xe 36 Limousine',
					),
					array(
						'key'          => 'field_xe36_features_items',
						'label'        => 'Danh sách lý do (mỗi dòng 1 mục)',
						'name'         => 'features_items',
						'type'         => 'textarea',
						'rows'         => 8,
						'instructions' => 'Định dạng: <code>Tiêu đề|Mô tả ngắn</code>. Phần mô tả có thể bỏ trống.',
					),
					array(
						'key'   => 'field_xe36_tab_reviews',
						'label' => 'Khách hàng nói gì',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'          => 'field_xe36_reviews_title',
						'label'        => 'Tiêu đề section',
						'name'         => 'reviews_title',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Khách hàng nói gì về chúng tôi',
					),
					array(
						'key'           => 'field_xe36_reviews_shortcode',
						'label'         => 'Shortcode Trustindex',
						'name'          => 'reviews_shortcode',
						'type'          => 'text',
						'default_value' => '[trustindex no-registration=google]',
						'instructions'  => 'Cài plugin Trustindex rồi cấu hình Google reviews. Shortcode mặc định: <code>[trustindex no-registration=google]</code>',
					),
					array(
						'key'   => 'field_xe36_tab_faq',
						'label' => 'Câu hỏi thường gặp',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'          => 'field_xe36_faq_title',
						'label'        => 'Tiêu đề section',
						'name'         => 'faq_title',
						'type'         => 'text',
						'instructions' => 'Ví dụ: Câu hỏi thường gặp',
					),
					array(
						'key'          => 'field_xe36_faq_items',
						'label'        => 'Danh sách câu hỏi',
						'name'         => 'faq_items',
						'type'         => 'textarea',
						'rows'         => 20,
						'instructions' => 'Mỗi mục: dòng đầu là câu hỏi, các dòng sau là câu trả lời. Cách các mục bằng dòng <code>---</code>. Dòng bắt đầu bằng <code>–</code> hoặc <code>-</code> sẽ thành danh sách.',
					),
					array(
						'key'   => 'field_xe36_tab_sections',
						'label' => 'Bật / tắt section',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'     => 'field_xe36_sections_message',
						'label'   => '',
						'name'    => '',
						'type'    => 'message',
						'message' => 'Section <strong>Đặt vé</strong> nên tắt khi form đã nằm trong Hero (tránh trùng). Thứ tự section do <code>inc/homepage/config.php</code>.',
					),
				),
				$section_fields,
				array(
					array(
						'key'   => 'field_xe36_tab_cta',
						'label' => 'CTA cuối trang',
						'name'  => '',
						'type'  => 'tab',
					),
					array(
						'key'   => 'field_xe36_cta_title',
						'label' => 'Tiêu đề CTA',
						'name'  => 'cta_title',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_xe36_cta_subtitle',
						'label' => 'Mô tả CTA',
						'name'  => 'cta_subtitle',
						'type'  => 'textarea',
						'rows'  => 3,
					),
					array(
						'key'   => 'field_xe36_cta_button_text',
						'label' => 'Nút đặt vé — chữ',
						'name'  => 'cta_button_text',
						'type'  => 'text',
					),
					array(
						'key'          => 'field_xe36_cta_button_url',
						'label'        => 'Nút đặt vé — link',
						'name'         => 'cta_button_url',
						'type'         => 'text',
						'instructions' => 'Được dùng: <code>#home-booking</code>, đường dẫn tương đối, hoặc URL đầy đủ.',
					),
					array(
						'key'           => 'field_xe36_cta_call_text',
						'label'         => 'Nút gọi hotline — chữ',
						'name'          => 'cta_call_text',
						'type'          => 'text',
						'default_value' => 'Gọi hotline',
						'instructions'  => 'Số điện thoại lấy từ Cài đặt site → Hotline.',
					),
					array(
						'key'           => 'field_xe36_cta_zalo_text',
						'label'         => 'Nút Zalo — chữ',
						'name'          => 'cta_zalo_text',
						'type'          => 'text',
						'default_value' => 'Nhắn Zalo',
						'instructions'  => 'Link Zalo lấy từ Cài đặt site → Zalo URL.',
					),
				)
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'xe36-homepage',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);
}
